iso:	generate_summary_table.py *.spthy
	./generate_summary_table.py ~/papers/iso/properties2.tex -2
	./generate_summary_table.py ~/papers/iso/properties3.tex -3
	./generate_summary_table.py ~/papers/iso/properties4.tex -4

